# Generated by Django 5.2.7 on 2025-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='W', max_length=1)),
            ],
        ),
    ]
